version: '2.1'

services:
  app:
    image: internetnl/internetnl
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    dns: 127.0.0.1
    depends_on:
      - redis
      - rabbitmq
      - postgres
      - routinator
    environment:
      - DEBUG=True
      - ENABLE_BATCH=${ENABLE_BATCH:-False}
      - ALLOWED_HOSTS=127.0.0.1

  redis:
    network_mode: host
    image: redis:alpine

  rabbitmq:
    network_mode: host
    image: rabbitmq:management-alpine

  postgres:
    network_mode: host
    image: postgres:alpine
    environment:
      - POSTGRES_USER=internetnl
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=internetnl_db1

  routinator:
    network_mode: host
    image: nlnetlabs/routinator
