# Generated by Django 3.2.20 on 2023-10-21 16:04

import checks.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0015_auto_20231020_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintesttls',
            name='mtasts_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='mtasts_policy_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='mtasts_policy_status',
            field=enumfields.fields.EnumIntegerField(enum=checks.models.MtaStsPolicyStatus, null=True),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='mtasts_policy_record',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='mtasts_record',
            field=checks.models.ListField(default=[]),
        ),
        migrations.AddField(
            model_name='domaintesttls',
            name='mtasts_score',
            field=models.IntegerField(null=True),
        ),
    ]
